heat_template_version: rocky

description: Create networks to split out Overcloud traffic

parameters:
  CtlplaneNetworkCidrs:
    type: json
    description: Cidrs for the ctlplane network.

resources:
  ExternalNetwork:
    type: OS::TripleO::Network::External
  InternalApiNetwork:
    type: OS::TripleO::Network::InternalApi
  StorageNetwork:
    type: OS::TripleO::Network::Storage
  StorageMgmtNetwork:
    type: OS::TripleO::Network::StorageMgmt
  TenantNetwork:
    type: OS::TripleO::Network::Tenant

  NetworkExtraConfig:
    type: OS::TripleO::Network::ExtraConfig


outputs:
  net_cidr_map:
    value:
      # NOTE(hjensas): If a network does not have any network_cidrs, fall back
      # to the ctlplane (provisioning) network.
      external:
        yaql:
          data:
            network_cidrs: {get_attr: [ExternalNetwork, network_cidrs]}
            ctlplane_cidrs: {get_param: CtlplaneNetworkCidrs}
          expression: switch(not isList($.data.network_cidrs) => $.data.ctlplane_cidrs, $.data.network_cidrs => $.data.network_cidrs)
      internal_api:
        yaql:
          data:
            network_cidrs: {get_attr: [InternalApiNetwork, network_cidrs]}
            ctlplane_cidrs: {get_param: CtlplaneNetworkCidrs}
          expression: switch(not isList($.data.network_cidrs) => $.data.ctlplane_cidrs, $.data.network_cidrs => $.data.network_cidrs)
      storage:
        yaql:
          data:
            network_cidrs: {get_attr: [StorageNetwork, network_cidrs]}
            ctlplane_cidrs: {get_param: CtlplaneNetworkCidrs}
          expression: switch(not isList($.data.network_cidrs) => $.data.ctlplane_cidrs, $.data.network_cidrs => $.data.network_cidrs)
      storage_mgmt:
        yaql:
          data:
            network_cidrs: {get_attr: [StorageMgmtNetwork, network_cidrs]}
            ctlplane_cidrs: {get_param: CtlplaneNetworkCidrs}
          expression: switch(not isList($.data.network_cidrs) => $.data.ctlplane_cidrs, $.data.network_cidrs => $.data.network_cidrs)
      tenant:
        yaql:
          data:
            network_cidrs: {get_attr: [TenantNetwork, network_cidrs]}
            ctlplane_cidrs: {get_param: CtlplaneNetworkCidrs}
          expression: switch(not isList($.data.network_cidrs) => $.data.ctlplane_cidrs, $.data.network_cidrs => $.data.network_cidrs)