- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-ceilometer-central:16.2
  config_volume: ceilometer
  puppet_tags: ceilometer_config
  step_config: 'include ::tripleo::profile::base::ceilometer::agent::polling

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-ceilometer-central:16.2
  config_volume: ceilometer
  puppet_tags: ceilometer_config
  step_config: 'include ::tripleo::profile::base::ceilometer::agent::notification

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-cinder-api:16.2
  config_volume: cinder
  puppet_tags: cinder_config,cinder_type,file,concat,file_line
  step_config: 'include ::tripleo::profile::base::cinder::api

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-cinder-api:16.2
  config_volume: cinder
  puppet_tags: cinder_config,file,concat,file_line
  step_config: 'include ::tripleo::profile::base::cinder::scheduler


    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-cinder-api:16.2
  config_volume: cinder
  puppet_tags: cinder_config,file,concat,file_line
  step_config: 'include ::tripleo::profile::base::lvm

    include ::tripleo::profile::pacemaker::cinder::volume

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-mariadb:16.2
  config_volume: clustercheck
  puppet_tags: file
  step_config: include ::tripleo::profile::pacemaker::clustercheck
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-collectd:16.2
  config_volume: collectd
  puppet_tags: collectd_client_config,exec
  step_config: include ::tripleo::profile::base::metrics::collectd
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-heat-api:16.2
  config_volume: heat
  puppet_tags: heat_plugin_opencontrail,ini_setting,create_ini_settings,inifile,heat_config,file,concat,file_line
  step_config: include ::tripleo::network::contrail::heat
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-glance-api:16.2
  config_volume: glance_api
  puppet_tags: glance_api_config,glance_api_paste_ini,glance_swift_config,glance_cache_config,glance_image_import_config
  step_config: 'include ::tripleo::profile::base::glance::api



    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-haproxy:16.2
  config_volume: haproxy
  puppet_tags: haproxy_config
  step_config: 'exec {''wait-for-settle'': command => ''/bin/true'' }

    class tripleo::firewall(){}; define tripleo::firewall::rule( $port = undef, $dport
    = undef, $sport = undef, $proto = undef, $action = undef, $state = undef, $source
    = undef, $iniface = undef, $chain = undef, $destination = undef, $extras = undef){}

    [''pcmk_bundle'', ''pcmk_resource'', ''pcmk_property'', ''pcmk_constraint'', ''pcmk_resource_default''].each
    |String $val| { noop_resource($val) }

    include ::tripleo::profile::pacemaker::haproxy_bundle'
  volumes: []
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-heat-api:16.2
  config_volume: heat_api
  puppet_tags: heat_config,file,concat,file_line
  step_config: 'include ::tripleo::profile::base::heat::api

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-heat-api-cfn:16.2
  config_volume: heat_api_cfn
  puppet_tags: heat_config,file,concat,file_line
  step_config: 'include ::tripleo::profile::base::heat::api_cfn

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-heat-api:16.2
  config_volume: heat
  puppet_tags: heat_config,file,concat,file_line
  step_config: 'include ::tripleo::profile::base::heat::engine

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-horizon:16.2
  config_volume: horizon
  puppet_tags: horizon_config
  step_config: 'include ::tripleo::profile::base::horizon

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-iscsid:16.2
  config_volume: iscsid
  puppet_tags: iscsid_config
  step_config: 'include ::tripleo::profile::base::iscsid

    '
  volumes:
  - /etc/iscsi:/etc/iscsi:z
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-keystone:16.2
  config_volume: keystone
  puppet_tags: keystone_config,keystone_domain_config
  step_config: '[''Keystone_user'', ''Keystone_endpoint'', ''Keystone_domain'', ''Keystone_tenant'',
    ''Keystone_user_role'', ''Keystone_role'', ''Keystone_service''].each |String
    $val| { noop_resource($val) }

    include ::tripleo::profile::base::keystone


    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-memcached:16.2
  config_volume: memcached
  puppet_tags: file
  step_config: 'include ::tripleo::profile::base::memcached

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-qdrouterd:16.2
  config_volume: metrics_qdr
  step_config: 'include ::tripleo::profile::base::metrics::qdr

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-mariadb:16.2
  config_volume: mysql
  puppet_tags: file
  step_config: '[''Mysql_datadir'', ''Mysql_user'', ''Mysql_database'', ''Mysql_grant'',
    ''Mysql_plugin''].each |String $val| { noop_resource($val) }

    exec {''wait-for-settle'': command => ''/bin/true'' }

    include ::tripleo::profile::pacemaker::database::mysql_bundle'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-neutron-server:16.2
  config_volume: neutron
  puppet_tags: neutron_config,neutron_api_config
  step_config: 'include tripleo::profile::base::neutron::server

    include ::tripleo::profile::base::database::mysql::client'
- config_image: contrail-openstack-neutron-init
  config_volume: neutron
  puppet_tags: neutron_plugin_opencontrail,ini_setting,create_ini_settings,neutron_config,neutron_api_config,inifile
  step_config: include ::tripleo::network::contrail::neutron_plugin
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-nova-api:16.2
  config_volume: nova
  puppet_tags: nova_config
  step_config: '[''Nova_cell_v2''].each |String $val| { noop_resource($val) }

    include tripleo::profile::base::nova::api

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-nova-api:16.2
  config_volume: nova
  puppet_tags: nova_config
  step_config: 'include tripleo::profile::base::nova::conductor

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-nova-api:16.2
  config_volume: nova_metadata
  puppet_tags: nova_config
  step_config: 'include tripleo::profile::base::nova::metadata

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-nova-api:16.2
  config_volume: nova
  puppet_tags: nova_config
  step_config: 'include tripleo::profile::base::nova::scheduler

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-nova-api:16.2
  config_volume: nova
  puppet_tags: nova_config
  step_config: 'include tripleo::profile::base::nova::vncproxy

    include ::tripleo::profile::base::database::mysql::client'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-cron:16.2
  config_volume: crond
  step_config: include ::tripleo::profile::base::logging::logrotate
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-placement-api:16.2
  config_volume: placement
  puppet_tags: placement_config
  step_config: 'include ::tripleo::profile::base::database::mysql::client

    include tripleo::profile::base::placement::api'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-rabbitmq:16.2
  config_volume: rabbitmq
  puppet_tags: file,file_line
  step_config: '[''Rabbitmq_policy'', ''Rabbitmq_user''].each |String $val| { noop_resource($val)
    }

    include ::tripleo::profile::pacemaker::rabbitmq_bundle'
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-redis:16.2
  config_volume: redis
  puppet_tags: exec
  step_config: 'include ::tripleo::profile::pacemaker::database::redis_bundle

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-rsyslog:16.2
  config_volume: rsyslog
  puppet_tags: rsyslog::generate_concat,concat::fragment
  step_config: include ::tripleo::profile::base::logging::rsyslog
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-swift-proxy-server:16.2
  config_volume: swift
  puppet_tags: swift_config,swift_proxy_config,swift_keymaster_config
  step_config: 'include ::tripleo::profile::base::swift::proxy

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-swift-proxy-server:16.2
  config_volume: swift_ringbuilder
  puppet_tags: swift_config,exec,fetch_swift_ring_tarball,extract_swift_ring_tarball,ring_object_device,swift::ringbuilder::create,tripleo::profile::base::swift::add_devices,swift::ringbuilder::rebalance,create_swift_ring_tarball,upload_swift_ring_tarball
  step_config: 'include ::tripleo::profile::base::swift::ringbuilder

    '
- config_image: satellite.mgmt.tmeprj2.comm.red.ibm.gsc:5000/default-dev-osp16-2-osp16_containers-swift-proxy-server:16.2
  config_volume: swift
  puppet_tags: swift_config,swift_container_config,swift_container_sync_realms_config,swift_account_config,swift_object_config,swift_object_expirer_config,rsync::server
  step_config: 'class xinetd() {}

    define xinetd::service($bind='''',$port='''',$server='''',$server_args='''') {}

    include ::tripleo::profile::base::swift::storage'
