collectd:
  collectd::plugin::virt::connection: qemu:///system
  tripleo.collectd.plugins.nova_compute:
  - virt
keystone:
  tripleo::profile::base::keystone::ceilometer_notification_topics:
  - notifications
rsyslog:
  tripleo_logging_sources_metrics_qdr:
  - file: /var/log/containers/qdrouterd/metrics_qdr.log
    startmsg.regex: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}(.[0-9]+
      \+[0-9]+)? [A-Z]+ \([a-z]+\) '
    tag: openstack.nova.consoleauth
  tripleo_logging_sources_nova_compute:
  - file: /var/log/containers/nova/nova-compute.log
    tag: openstack.nova.compute
