- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 0
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  vars:
    bootstrap_server_id: 9f9ad6ec-fa12-48c7-ab06-6bc91348e5da
    step: '0'
    deploy_identifier: DeployIdentifier
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Controller/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'Controller'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
    - include_tasks: ContrailController/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'ContrailController'
      tags:
        - always
    - include_tasks: ContrailSriov/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'ContrailSriov'
      tags:
        - always
    - include_tasks: ContrailDpdk/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'ContrailDpdk'
      tags:
        - always
    - include_tasks: ComputeNFV/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'ComputeNFV'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step0
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 1
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  vars:
    bootstrap_server_id: 9f9ad6ec-fa12-48c7-ab06-6bc91348e5da
    step: '1'
    deploy_identifier: DeployIdentifier
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Controller/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'Controller'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
    - include_tasks: ContrailController/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'ContrailController'
      tags:
        - always
    - include_tasks: ContrailSriov/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'ContrailSriov'
      tags:
        - always
    - include_tasks: ContrailDpdk/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'ContrailDpdk'
      tags:
        - always
    - include_tasks: ComputeNFV/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'ComputeNFV'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step1
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 2
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  vars:
    bootstrap_server_id: 9f9ad6ec-fa12-48c7-ab06-6bc91348e5da
    step: '2'
    deploy_identifier: DeployIdentifier
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Controller/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'Controller'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
    - include_tasks: ContrailController/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'ContrailController'
      tags:
        - always
    - include_tasks: ContrailSriov/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'ContrailSriov'
      tags:
        - always
    - include_tasks: ContrailDpdk/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'ContrailDpdk'
      tags:
        - always
    - include_tasks: ComputeNFV/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'ComputeNFV'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step2
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 3
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  vars:
    bootstrap_server_id: 9f9ad6ec-fa12-48c7-ab06-6bc91348e5da
    step: '3'
    deploy_identifier: DeployIdentifier
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Controller/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'Controller'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
    - include_tasks: ContrailController/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'ContrailController'
      tags:
        - always
    - include_tasks: ContrailSriov/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'ContrailSriov'
      tags:
        - always
    - include_tasks: ContrailDpdk/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'ContrailDpdk'
      tags:
        - always
    - include_tasks: ComputeNFV/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'ComputeNFV'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step3
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 4
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  vars:
    bootstrap_server_id: 9f9ad6ec-fa12-48c7-ab06-6bc91348e5da
    step: '4'
    deploy_identifier: DeployIdentifier
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Controller/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'Controller'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
    - include_tasks: ContrailController/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'ContrailController'
      tags:
        - always
    - include_tasks: ContrailSriov/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'ContrailSriov'
      tags:
        - always
    - include_tasks: ContrailDpdk/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'ContrailDpdk'
      tags:
        - always
    - include_tasks: ComputeNFV/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'ComputeNFV'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step4
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 5
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  vars:
    bootstrap_server_id: 9f9ad6ec-fa12-48c7-ab06-6bc91348e5da
    step: '5'
    deploy_identifier: DeployIdentifier
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Controller/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'Controller'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
    - include_tasks: ContrailController/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'ContrailController'
      tags:
        - always
    - include_tasks: ContrailSriov/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'ContrailSriov'
      tags:
        - always
    - include_tasks: ContrailDpdk/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'ContrailDpdk'
      tags:
        - always
    - include_tasks: ComputeNFV/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'ComputeNFV'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step5
